# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SaWu20W0VbBJ40WL4DJXvfiZReCckVVx
"""

import re
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, BarColumn, TextColumn
from rich.text import Text

console = Console()

def check_password_strength(password):
    score = 0
    suggestions = []

    if len(password) >= 8:
        score += 1
    else:
        suggestions.append("❌ Minimum 8 characters")

    if re.search(r"[A-Z]", password):
        score += 1
    else:
        suggestions.append("❌ Add uppercase letter (A-Z)")

    if re.search(r"[a-z]", password):
        score += 1
    else:
        suggestions.append("❌ Add lowercase letter (a-z)")

    if re.search(r"[0-9]", password):
        score += 1
    else:
        suggestions.append("❌ Add number (0-9)")

    if re.search(r"[@#$%!&*]", password):
        score += 1
    else:
        suggestions.append("❌ Add special character (@#$%!&*)")

    return score, suggestions


# =========================
# MAIN PROGRAM
# =========================
console.print(Panel.fit(
    "🔐 PASSWORD STRENGTH CHECKER 🔐\nBeginner Python Project • 2025",
    style="bold cyan"
))

password = console.input("[bold yellow]Enter your password:[/] ")

score, suggestions = check_password_strength(password)

# Strength message
if score <= 2:
    strength = "[bold red]WEAK PASSWORD ❌[/]"
elif score == 3:
    strength = "[bold yellow]MEDIUM PASSWORD ⚠️[/]"
else:
    strength = "[bold green]STRONG PASSWORD ✅[/]"

console.print("\n" + strength)
console.print(f"[bold]Score:[/] {score}/5\n")

# Progress bar
with Progress(
    TextColumn("[progress.description]{task.description}"),
    BarColumn(),
    TextColumn("{task.completed}/5"),
) as progress:
    task = progress.add_task("Password Strength", total=5)
    progress.update(task, completed=score)

# Suggestions panel
if suggestions:
    suggestion_text = "\n".join(suggestions)
    console.print(Panel(
        suggestion_text,
        title="🔧 Suggestions to Improve",
        border_style="red"
    ))
else:
    console.print(Panel(
        "🎉 Your password is strong and secure!",
        border_style="green"
    ))